### ISSUE TITLE
Contact info? Re: Boxee replacement server

### ISSUE THREAD

**Issue by nicholasserra** [cigamit/boxeehack#41]
Hey Jimmy, 

Can't seem to find contact info for you anywhere. Boxee finally pulled the plug on their servers, taking down all boxee boxes still being used. I started trying to create my own replacement server by sniffing traffic from my boxes, but then stumbled upon your post via the wayback machine on your forums. Seems you made some progress in a replacement server just for this occasion. Is that code anywhere? I'd love to give it a try and keep these boxee boxes online.

Thanks!

**Comment by makeitworst** [comment]
nicholasserra ... if you are trying to get server info from the clown who years ago promised/claimed he was copying and saving D-Link Server data to save us all by putting up a Boxee Box Server, don't hold your breath seeing anything. I confronted that guy (don't recall his name) a couple of years ago when D-Link shut down the "login servers" (they've done something different 2 weeks ago that did in the last BB's) and basically he sputtered and sputtered and finally admitted he'd actually done NOTHING. it was probably all the "fake out" from the beginning to get some false 15 minutes of fame. My wife worked for D-Link for 18 years and I spoke to the VP of Product Development about the Servers two years ago (he's gone from D-Link now) and there was no way of "copying" the program or the database ever. It was all a shame by this clown. It was casting D-Link $15K USD per year to run those servers and that's the reason they were shut down.

Best thing for you to do is go to the website still up that helps you Root your Boxee Box, but note if you have a HW ver A1, it won't work, only later A2 and B versions will. Google for a site named "How to obtain root, install and run XBMC on D-Link Boxee Box" 05 Dec , 2013

One other thing the XBMC patch run off a USB 2.0 stick will not work now. Rooting is the only remedy.

Good Luck

**Comment by nicholasserra** [comment]
I'm already in contact with him and he's already provided details to his hosted boxee server clone, and it seems to be working so far. He's been very responsive and helpful. Sorry if you had a bad experience. Hoping to have his code tweaked and online to restore normal functionality very soon. Head over to boxee subreddit for some more folks providing some fixes.

**Comment by makeitworst** [comment]
nicholasserra - how about leaving a full URL for this "boxee subreddit" site, I haven't a clue how to find it with the limited info you've left above.

**Comment by nicholasserra** [comment]
Sorry I assumed Reddit was a popular enough site that it didn't need explanation. https://www.reddit.com/r/boxee/

**Comment by makeitworst** [comment]
Hey thanks very much. I'll look it up

**Comment by cigamit** [comment]
I am back from Toyko.  I will see about creating a Repo next week with the Boxee Server replacement in it.  My issue was that my Boxee died long ago.  I bought 2 replacements off of ebay, but both were bricked on arrival so I eventually gave up and just moved to an Amazon FireTV running XBMC.  The Boxee hardware was getting a bit dated.

As for makeitworst, at this point he was banned on the old forums for being abusive, blocked via my email for the same, and now he is blocked on here and reddit from contacting me.  Every post / email he has ever done has been basically the same as above, almost verbatim.  Grandiose posts about his wife working for DLink and other puffed up claims.  He himself has never done anything to further Boxee development (he doesn't seem to have any technical expertise) and has instead just made demands of me and my time.  I am busy enough as it is.  No reason to deal with people like him.

I find his comment about the VP funny, since most VPs with be the last to know if something was technologically possible.  As for the Boxee Server Replacement, it was actually fairly easy.  All that was required was to change the local DNS for the Boxee domains to point to my server.  The Boxee was then sending all requests there.  So using a simple nginx rewrite, I had it redirect every request to a single PHP script.  This script took the request, logged it, and then made the request directly to the real Boxee servers as if it was the Boxee.  I then logged the responses to all the requests.  No different really than proxying or a simple Man in the Middle.

With this, I got the basic formatting on responses the Boxee should receive.  I then started creating actual scripts to reply with the correct data structure.  The main issue I ran into was pulling the Movie info.  Its been a while, but I think at the time I couldn't pull movie info from IMDB, and instead was pulling it form TMDB, but that left me with not being able to pull TV Show info.  We will most likely have to update that script anyways, as their API has probably changed since I last touched it.

I also have all the apps and ISOs cached in case they are needed.

**Comment by nicholasserra** [comment]
Yeah that's pretty much all in line with what I assumed with those comments. Thanks for clearing that up! Please let me know when you create that repo. I'll probably fork it, make login return 200 no matter what, and toss it all behind a CDN just to restore basic functionality and get some apps working again. Excited to get my boxes back online without doing any rooting or other hacks.

Thank you!
